version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    volumes:
      - ./:/workspace:cached
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URI=postgresql://postgres:postgres@db/postgres
      - DATABASE_URI_TEST=postgresql://postgres:postgres@db/postgres_test

    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: dockerfiles/db.dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
