version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    volumes:
      - ./:/workspace:cached
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@web-db:5432/web
      - DATABASE_URI_TEST=postgresql://postgres:postgres@web-db:5432/web_test

    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    container_name: fastapi-app
    ports:
      - 8002:8000
    depends_on:
      - web-db
  web-db:
    build:
      context: ./
      dockerfile: dockerfiles/db.dockerfile
    container_name: fastapi-db
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
