version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.11 # Specify your desired stable Python version
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db/postgres

    command: sleep infinity # Keeps the app container running

    network_mode: service:db # Connects app to the database network
    # Uncomment to use a non-root user for all processes.
    # user: vscode

  db:
    image: postgres:15.4 # Specify the stable PostgreSQL version
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
