version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: dockerfiles/app.dockerfile
    volumes:
      - ..:/workspace:cached

    environment:
      DATABASE_URI: postgresql://postgres:postgres@db/web
      DATABASE_URI_TEST: postgresql://postgres:postgres@db/web_test

    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db

  db:
    build:
      context: ..
      dockerfile: dockerfiles/db.dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
